"""initial multitenant schema: organizations, roles, users, sessions, reset tokens

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-15

Authored explicitly (not autogenerated) because the dev machine had no live
Postgres to diff against. Mirrors the SQLAlchemy models 1:1 — verify with
``flask db upgrade`` once a database is available.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

org_status = postgresql.ENUM(
    "TRIAL", "ACTIVE", "PAST_DUE", "SUSPENDED", name="org_status", create_type=False
)
user_role = postgresql.ENUM(
    "SUPER_ADMIN", "ADMIN", "STAFF", "CUSTOMER", name="user_role", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    org_status.create(bind, checkfirst=True)
    user_role.create(bind, checkfirst=True)

    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", org_status, nullable=False),
        sa.Column("logo_url", sa.String(length=500)),
        sa.Column("primary_color", sa.String(length=20)),
        sa.Column("plan", sa.String(length=50)),
        sa.Column("billing_customer_id", sa.String(length=120)),
        sa.Column("subscription_id", sa.String(length=120)),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True)),
        sa.Column("paystack_secret_encrypted", sa.Text()),
        sa.Column("paystack_public_key", sa.String(length=120)),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_organizations_slug", "organizations", ["slug"], unique=True)

    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255)),
        sa.Column("permissions", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_roles_org_name"),
    )
    op.create_index("ix_roles_org", "roles", ["organization_id"])

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=40)),
        sa.Column("role", user_role, nullable=False),
        sa.Column("custom_role_id", sa.Uuid()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["custom_role_id"], ["roles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "email", name="uq_users_org_email"),
        sa.UniqueConstraint("organization_id", "username", name="uq_users_org_username"),
    )
    op.create_index("ix_users_org", "users", ["organization_id"])

    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sessions_token_hash", "sessions", ["token_hash"], unique=True)
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])

    op.create_table(
        "password_reset_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index("ix_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"])


def downgrade() -> None:
    op.drop_table("password_reset_tokens")
    op.drop_table("sessions")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("organizations")
    bind = op.get_bind()
    user_role.drop(bind, checkfirst=True)
    org_status.drop(bind, checkfirst=True)
